### ISSUE TITLE
Error loading book packages in new baseline Pharo 10 using metacello command

### ISSUE THREAD

**Issue by recursive68** [Apress/agile-ai-in-pharo#9]
Hi,

Trying to load the books packages in a new baseline Pharo 10 64 bit image on OSX, using the metacello command in the book and it fails with this error:

IceGenericError: bad packet length 

visitGenericError: anError

	IceGenericError new
		messageText: anError messageText;
		wrappedException: anError;
		signal

Seems to be an issue cloning the repo to create a new local copy. If I dig into the stack trace, this section of createIcebergRepositoryWithFallbackFor: remote url: remoteUrl
is highlighted:

	on: IceAuthenticationError do: [ :e |
		self traceCr: ('I got an error while cloning: {1}. I will try to clone the HTTPS variant.' format: { e messageText }). 
		urlToUse := remote httpsUrl.
		e retry ]

If I kill that session and debug windows, and try rerunning the metacello command it does appear to work successfully but whether that means it has  loaded the packages correctly I don't know.

Also if I try and run the Roassal Plugin > Load Artifical Intelligence Support (NN and GA) it also fails with dependency errors. 

Thanks

**Comment by coentjo** [comment]
Dear recursive,
in my fork coentjo/agile-ai-in-pharo I encountered the same, if I remember correctly: in newest pharo roassal3 is used instead of roassal2: by changing that in the baseline (probably just removing roassal2) the msg is fixed. After that, graph-scripts have to be adjusted: in the 'coentjo'-fork in history you can find some examples, if desired. ​

best regards,
met vriendelijke groet,
Coen Crombach
________________________________
From: recursive68 ***@***.***>
Sent: Saturday, November 5, 2022 6:08:45 PM
To: Apress/agile-ai-in-pharo ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Apress/agile-ai-in-pharo] Error loading book packages in new baseline Pharo 10 using metacello command (Issue #9)


Hi,

Trying to load the books packages in a new baseline Pharo 10 64 bit image on OSX, using the metacello command in the book and it fails with this error:

IceGenericError: bad packet length

visitGenericError: anError

IceGenericError new
        messageText: anError messageText;
        wrappedException: anError;
        signal


Seems to be an issue cloning the repo to create a new local copy. If I dig into the stack trace, this section of createIcebergRepositoryWithFallbackFor: remote url: remoteUrl
is highlighted:

on: IceAuthenticationError do: [ :e |
        self traceCr: ('I got an error while cloning: {1}. I will try to clone the HTTPS variant.' format: { e messageText }).
        urlToUse := remote httpsUrl.
        e retry ]


If I kill that session and debug windows, and try rerunning the metacello command it does appear to work successfully but whether that means it has loaded the packages correctly I don't know.

Also if I try and run the Roassal Plugin > Load Artifical Intelligence Support (NN and GA) it also fails with dependency errors.

Thanks

—
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FApress%2Fagile-ai-in-pharo%2Fissues%2F9&data=05%7C01%7CC.Crombach%40Fontys.nl%7C7ff2adcb12cb4fd123c908dabf5066d6%7Cc66b6765b7944a2b84ed845b341c086a%7C0%7C0%7C638032649292604867%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=cRHHDV%2F1FvMDw12ntS5Eghj1toWFhb%2BBk%2BpFoYzVugA%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAN5OG6UPRGX2RZSZFGSYGLWG2IB3ANCNFSM6AAAAAARYAIOUY&data=05%7C01%7CC.Crombach%40Fontys.nl%7C7ff2adcb12cb4fd123c908dabf5066d6%7Cc66b6765b7944a2b84ed845b341c086a%7C0%7C0%7C638032649292604867%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=2l9%2BGtB%2BiixsYiS1Bz2RTuKELjXpJ9Xvb%2BQmD81zdlc%3D&reserved=0>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

======================================================================================================================================== E-maildisclaimer: Aan dit bericht, waaronder ook de eventuele bijlagen worden bedoeld, kunnen geen rechten worden ontleend. Dit bericht is uitsluitend bestemd voor de geadresseerde en bevat persoonlijke en vertrouwelijke informatie. Het bekend maken, kopieren en verspreiden van een bericht dat niet voor u bestemd is, is niet toegestaan. Als u dit bericht per ongeluk heeft ontvangen, verzoeken wij u vriendelijk het direct te vernietigen en de afzender te informeren. Twijfelt u over de juistheid of volledigheid van dit bericht? Neem dan contact op met de afzender. ======================================================================================================================================== This message and any associated attachments cannot be deemed as legally binding under any circumstances. This message is intended for the exclusive use of the person(s) mentioned as recipient(s) and contains personal and confidential information. Directly or indirectly copying, disclosing, distributing, printing, publicising and/or in any way using this message or any part thereof by any means is strictly prohibited if you are not the intended recipient(s). If you have received this message in error, please notify the sender and delete this message from your system immediately. If you are in doubt regarding the correctness and/or completeness of this message, please contact the sender.

**Comment by recursive68** [comment]
Hi Coen,

Thanks for the information about Roassal. Did you see in the Iceberg error when loading the agile-ai-in-pharo packages in Pharo 10 too ?

thanks again

**Comment by coentjo** [comment]
Sorry, did not have time to try it out yet...
(cannot remember exact error)

best regards,
met vriendelijke groet,
Coen Crombach
________________________________

**Comment by coentjo** [comment]
Hi, 
Sorry it took so long... 
I just created a fresh Pharo10-image, evaluated
```
Metacello new
    baseline: 'AgileArtificialIntelligence';
    repository: 'github://apress/agile-ai-in-pharo:master/src';
    onConflictUseIncoming;
    load.
```
Ran without problems on my (Intel) Mac Air 2019. 
So my system does not have this problem (any more?). Could it be that the problem is solved?

**Comment by recursive68** [comment]
Hi,

Thanks for looking at it. I am afraid I am still seeing an error. Downloaded a new Pharo 10 64 bit image using PharoLauncher and evaluated your Metacello command and it fails with this error:

IceGenericError: error reading from the zlib stream

visitGenericError: anError

	IceGenericError new
		messageText: anError messageText;
		wrappedException: anError;
		signal

Update:

Just done a google search and found this:

https://github.com/pharo-project/pharo/issues/11481 

It's an issue with Pharo 10 build. I've now downloaded the latest Pharo 10 snapshot build 535 and Agile-ai package now loads successfully.


Thanks for looking at it though.
